using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AceLand.Injection.SourceGenerator
{
    internal static class Emitter
    {
        const string N = "global::AceLand.Injection";

        public static string EmitPlan(TypeModel m, string version)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated by AceLand.Injection.SourceGenerator />");
            sb.AppendLine("#pragma warning disable CS0618");

            var ns = m.Symbol.ContainingNamespace.IsGlobalNamespace
                ? null : m.Symbol.ContainingNamespace.ToDisplayString();
            if (ns != null) sb.AppendLine($"namespace {ns}\n{{");

            var indent = ns != null ? "    " : "";
            var closers = new Stack<string>();

            if (m.Nested)
            {
                // reopen the (partial) containing types
                var nest = new List<INamedTypeSymbol>();
                for (var t = m.Symbol; t != null; t = t.ContainingType) nest.Add(t);
                nest.Reverse();
                foreach (var t in nest)
                {
                    var kind = t.TypeKind == TypeKind.Struct ? "struct" : "class";
                    sb.AppendLine($"{indent}partial {kind} {t.Name}");
                    sb.AppendLine($"{indent}{{");
                    closers.Push(indent + "}");
                    indent += "    ";
                }
            }

            var className = m.Nested ? "__AceLandInjector"
                                     : "Injector_" + m.DisplayName.Replace('.', '_').Replace('+', '_');
            var access = m.Nested ? "internal" : "internal";

            sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"AceLand.Injection.SourceGenerator\", \"{version}\")]");
            sb.AppendLine($"{indent}{access} sealed class {className} : {N}.IInjectorPlan");
            sb.AppendLine($"{indent}{{");
            var i2 = indent + "    ";
            sb.AppendLine($"{i2}public static readonly {className} Instance = new {className}();");
            sb.AppendLine($"{i2}public global::System.Type TargetType => typeof({m.FullName});");

            var canCreate = m.Constructor != null;
            sb.AppendLine($"{i2}public bool CanCreateInstance => {(canCreate ? "true" : "false")};");
            sb.AppendLine($"{i2}public bool HasMultipleConstructors => {(m.HasMultipleConstructors ? "true" : "false")};");

            EmitDependencies(sb, i2, m);
            EmitCreate(sb, i2, m, canCreate);
            EmitInject(sb, i2, m);

            sb.AppendLine($"{indent}}}");

            while (closers.Count > 0) sb.AppendLine(closers.Pop());
            if (ns != null) sb.AppendLine("}");
            return sb.ToString();
        }

        static void EmitDependencies(StringBuilder sb, string i, TypeModel m)
        {
            var items = new List<string>();

            if (m.Constructor != null)
                foreach (var p in m.Constructor.Parameters)
                    items.Add($"new {N}.InjectDependency(typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), " +
                              $"{N}.DependencyKind.Constructor, \"{p.Name}\", {(p.HasExplicitDefaultValue ? "true" : "false")})");

            foreach (var mem in m.Members)
            {
                if (mem.IsComponent)
                    items.Add($"new {N}.InjectDependency(typeof({mem.TypeFullName}), {N}.DependencyKind.Component, " +
                              $"\"{mem.Name}\", {Bool(mem.Optional)}, null, {N}.ComponentSource.{mem.ComponentSource})");
                else
                    items.Add($"new {N}.InjectDependency(typeof({mem.TypeFullName}), " +
                              $"{N}.DependencyKind.{(mem.IsProperty ? "Property" : "Field")}, \"{mem.Name}\", " +
                              $"{Bool(mem.Optional)}, {mem.IdLiteral ?? "null"})");
            }

            foreach (var me in m.Methods)
                foreach (var (type, name) in me.Parameters)
                    items.Add($"new {N}.InjectDependency(typeof({type}), {N}.DependencyKind.MethodParameter, " +
                              $"\"{me.Name}({name})\", {Bool(me.Optional)}, {me.IdLiteral ?? "null"})");

            sb.AppendLine($"{i}static readonly {N}.InjectDependency[] s_deps = new {N}.InjectDependency[]");
            sb.AppendLine($"{i}{{");
            foreach (var it in items) sb.AppendLine($"{i}    {it},");
            sb.AppendLine($"{i}}};");
            sb.AppendLine($"{i}public {N}.InjectDependency[] Dependencies => s_deps;");
        }

        static void EmitCreate(StringBuilder sb, string i, TypeModel m, bool canCreate)
        {
            sb.AppendLine($"{i}public object CreateInstance({N}.IObjectResolver r, object[] extraArgs)");
            sb.AppendLine($"{i}{{");
            if (!canCreate)
                sb.AppendLine($"{i}    throw new {N}.InjectionException(\"{m.DisplayName} cannot be constructed by the container.\");");
            else
            {
                var args = m.Constructor.Parameters.Select(p =>
                {
                    var t = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    return p.HasExplicitDefaultValue
                        ? $"{N}.InjectorPlanUtil.Optional<{t}>(r)"
                        : $"{N}.InjectorPlanUtil.Arg<{t}>(r, extraArgs, \"{m.DisplayName}\", \"{p.Name}\")";
                });
                sb.AppendLine($"{i}    return new {m.FullName}({string.Join(", ", args)});");
            }
            sb.AppendLine($"{i}}}");
        }

        static void EmitInject(StringBuilder sb, string i, TypeModel m)
        {
            sb.AppendLine($"{i}public void Inject(object instance, {N}.IObjectResolver r)");
            sb.AppendLine($"{i}{{");
            sb.AppendLine($"{i}    var t = ({m.FullName})instance;");

            foreach (var mem in m.Members)
            {
                if (mem.IsComponent)
                {
                    sb.AppendLine($"{i}    t.{mem.Name} = ({mem.TypeFullName}){N}.ComponentInjection.Resolve(" +
                                  $"t, {N}.ComponentSource.{mem.ComponentSource}, typeof({mem.TypeFullName}), " +
                                  $"{Bool(mem.Optional)}, {Bool(mem.IncludeInactive)}, \"{mem.Name}\");");
                }
                else if (mem.Optional)
                {
                    sb.AppendLine($"{i}    t.{mem.Name} = {N}.InjectorPlanUtil.Optional<{mem.TypeFullName}>" +
                                  $"(r, {mem.IdLiteral ?? "null"});");
                }
                else
                {
                    sb.AppendLine($"{i}    t.{mem.Name} = {N}.InjectorPlanUtil.Required<{mem.TypeFullName}>" +
                                  $"(r, \"{m.DisplayName}\", \"{mem.Name}\", {mem.IdLiteral ?? "null"});");
                }
            }

            foreach (var me in m.Methods)
            {
                var args = me.Parameters.Select(p => me.Optional
                    ? $"{N}.InjectorPlanUtil.Optional<{p.type}>(r, {me.IdLiteral ?? "null"})"
                    : $"{N}.InjectorPlanUtil.Required<{p.type}>(r, \"{m.DisplayName}\", \"{me.Name}\", {me.IdLiteral ?? "null"})");
                sb.AppendLine($"{i}    t.{me.Name}({string.Join(", ", args)});");
            }

            sb.AppendLine($"{i}}}");
        }

        static string Bool(bool b) => b ? "true" : "false";

        // ------------------------------------------------------------------ module initializer

        public static string EmitModule(string assemblyName, List<TypeModel> models, string version,
                                        bool emitPolyfill, bool hasUnityEngine)
        {
            var safe = new string((assemblyName ?? "Assembly")
                .Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray());

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated by AceLand.Injection.SourceGenerator />");
            sb.AppendLine("#if !ACELAND_INJECTION_NO_CODEGEN");
            sb.AppendLine();

            // ── polyfill: Unity's netstandard2.1 profile has no ModuleInitializerAttribute ──
            // Same define guards the attribute usage below, so disabling one never orphans the other.
            if (emitPolyfill)
            {
                sb.AppendLine("#if !ACELAND_INJECTION_NO_MODULE_INIT");
                sb.AppendLine("namespace System.Runtime.CompilerServices");
                sb.AppendLine("{");
                sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
                sb.AppendLine("    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }");
                sb.AppendLine("}");
                sb.AppendLine("#endif");
                sb.AppendLine();
            }

            sb.AppendLine("namespace AceLand.Injection.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"AceLand.Injection.SourceGenerator\", \"{version}\")]");
            if (hasUnityEngine)
                sb.AppendLine("    [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine($"    internal static class InjectorModule_{safe}");
            sb.AppendLine("    {");
            sb.AppendLine("        static bool s_initialized;");
            sb.AppendLine();
            sb.AppendLine("#if !ACELAND_INJECTION_NO_MODULE_INIT");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("#endif");
            if (hasUnityEngine)
                sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(" +
                              "global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        internal static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (s_initialized) return;");
            sb.AppendLine("            s_initialized = true;");
            foreach (var m in models)
                sb.AppendLine($"            global::AceLand.Injection.InjectorPlanRegistry.Register({PlanAccess(m)});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            return sb.ToString();
        }

        static string PlanAccess(TypeModel m)
        {
            if (m.Nested) return $"{m.FullName}.__AceLandInjector.Instance";

            var ns = m.Symbol.ContainingNamespace.IsGlobalNamespace
                ? "global::"
                : $"global::{m.Symbol.ContainingNamespace}.";
            return ns + "Injector_" + m.DisplayName.Replace('.', '_').Replace('+', '_') + ".Instance";
        }
    }
}